environment:
  global:
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      ARCH: "64"
      PYTHON_VERSION: "3.6"
    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "37"
      ARCH: "64"
      PYTHON_VERSION: "3.7"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels omnia
  - conda config --add channels janschulz
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda update -y --all
  - activate
  - conda install -y python=%PYTHON_VERSION% conda-build jinja2

build: false

test_script:
  - activate base
  - conda build devtools\\conda-recipe --python=%PYTHON_VERSION% 
